server:
  port: 8082   # change per service

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/XE
    username: INVENTORY_USER
    password: inv123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
    show-sql: true
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8095/realms/microservices-realm
          jwk-set-uri: http://keycloak:8080/realms/microservices-realm/protocol/openid-connect/certs

keycloak:
   server-url: http://keycloak:8080
   realm: microservices-realm
   admin-client-id: inventory-admin
   admin-client-secret: MXrleUgNxUfVFWonFCn4ntpGiE983KX5

springdoc:
 swagger-ui:
   path: /swagger-ui/index.html
   oauth:
     client-id: swagger-ui
     use-pkce-with-authorization-code-grant: true

logging:
  level:
    root: DEBUG
